-- Hand-written (unlike 01-seed.sql, not generated by tools/seed-gen — this
-- is deliberately small, not realistic/varied). A second database on the
-- same Postgres server, existing solely so the axum demo's SECOND_SOURCE=1
-- "reporting" source (implementations/rust/axum/examples/demo.rs) has real,
-- visibly different data to show when the frontend's source selector
-- switches to it — proving multi-source browsing, not just multi-source
-- routing against one dataset twice.

drop database if exists ashurbanipal_reporting;
create database ashurbanipal_reporting owner ashurbanipal;

\connect ashurbanipal_reporting

create table daily_revenue (
    day date not null,
    region text not null,
    revenue_cents bigint not null,
    primary key (day, region)
);
insert into daily_revenue (day, region, revenue_cents) values
    ('2026-08-01', 'us-east', 483210),
    ('2026-08-01', 'eu-west', 219044),
    ('2026-08-02', 'us-east', 501200),
    ('2026-08-02', 'eu-west', 198765),
    ('2026-08-03', 'us-east', 476590);

create table campaigns (
    id bigint generated always as identity primary key,
    name text not null,
    channel text not null,
    clicks integer not null default 0,
    conversions integer not null default 0
);
insert into campaigns (name, channel, clicks, conversions) values
    ('back-to-school', 'email', 14032, 812),
    ('back-to-school', 'social', 39201, 1190),
    ('autumn-sale', 'search', 22110, 943);
