#!/bin/sh
set -eu

# Regenerates docs/feature-backlog/README.md from the `> **Status:**` header
# line each NN-*.md carries, so "what's open vs. shipped" is one grep and one
# rendered table instead of 31 freeform prose lines.
#
#   backlog-index.sh          # verify README.md is current, exit 1 if stale
#   backlog-index.sh --fix    # rewrite README.md
#
# HEADER CONTRACT (CI-enforced via `mise run docs`; also stated in the
# generated README's "Adding an entry" section for contributors):
#
# One blockquote line, directly under the `# Title`, fields joined by " · ":
#
#   > **Status:** OPEN · **Area:** frontend
#   > **Status:** DONE · **Area:** frontend, docs · **Ref:** shipped 2026-09-05
#   > **Status:** PARTIAL · **Area:** rust, ports · **Ref:** <what remains>
#   > **Status:** REFERENCE · **Area:** docs · **Ref:** <why it's not a task>
#
# - Status is one of: OPEN PARTIAL DONE REFERENCE DECLINED.
# - Area is one or more of: frontend rust ports conformance spec infra docs.
# - Ref is free text. It is rendered for PARTIAL/DONE/REFERENCE/DECLINED and
#   IGNORED for OPEN — put an OPEN item's scheduling nuance in the doc body.
# - Do not use the literal " · " sequence inside a field value.

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
dir="$root/docs/feature-backlog"
out="$dir/README.md"

fix=0
if [ "${1:-}" = "--fix" ]; then
    fix=1
elif [ "$#" -ne 0 ]; then
    printf '%s\n' "usage: $0 [--fix]" >&2
    exit 2
fi

generated=$(node - "$dir" <<'EOF'
const fs = require("fs");
const path = require("path");
const dir = process.argv[2];

const ORDER = ["OPEN", "PARTIAL", "DONE", "REFERENCE", "DECLINED"];
const HEADING = {
  OPEN: "Open",
  PARTIAL: "Partial",
  DONE: "Done",
  REFERENCE: "Reference",
  DECLINED: "Declined",
};

// A table cell: collapse newlines, escape the column separator.
const esc = (s) => s.replace(/\s*\n\s*/g, " ").replace(/\|/g, "\\|").trim();

const files = fs
  .readdirSync(dir)
  .filter((f) => /^\d+-.*\.md$/.test(f))
  .sort((a, b) => parseInt(a) - parseInt(b));

const rows = [];
const errors = [];
for (const file of files) {
  const num = file.match(/^(\d+)-/)[1];
  const text = fs.readFileSync(path.join(dir, file), "utf8").replace(/^\uFEFF/, "");
  const title = (text.match(/^#\s+(.+?)\s*#*\s*$/m) || [])[1];
  if (!title) {
    errors.push(`${file}: no '# Title' line`);
    continue;
  }
  const line = (text.match(/^>\s*\*\*Status:\*\*.*$/m) || [])[0];
  if (!line) {
    errors.push(`${file}: no '> **Status:**' header line`);
    continue;
  }
  // Fields are `**Key:** value` joined by " · ". Each value runs up to the
  // next ` · **Key:**` boundary or end of line, so a value may itself
  // contain a "·" (even " · ") without being truncated.
  const body = line.replace(/^>\s*/, "");
  const field = (key) => {
    const m = body.match(
      new RegExp(`\\*\\*${key}:\\*\\*\\s*(.*?)\\s*(?=·\\s*\\*\\*[A-Za-z]+:\\*\\*|$)`, "s"),
    );
    return m ? m[1].trim() : "";
  };
  const fields = { status: field("Status"), area: field("Area"), ref: field("Ref") };
  const status = fields.status.toUpperCase();
  if (!ORDER.includes(status)) {
    errors.push(`${file}: Status must be one of ${ORDER.join(" ")} (got '${fields.status || ""}')`);
    continue;
  }
  rows.push({
    num,
    file,
    title: esc(title),
    status,
    area: esc(fields.area || "—"),
    ref: esc(fields.ref || ""),
  });
}

if (errors.length) {
  process.stderr.write(errors.join("\n") + "\n");
  process.exit(1);
}

const count = (s) => rows.filter((r) => r.status === s).length;
const summary = ORDER.filter((s) => count(s)).map((s) => {
  const label = `${count(s)} ${s.toLowerCase()}`;
  return s === "OPEN" ? `**${label}**` : label;
});

const out = [];
out.push("<!-- generated by tools/backlog-index.sh — run `mise run docs:backlog-index` to refresh -->");
out.push("# Feature backlog — index");
out.push("");
out.push(`${rows.length} entries · ${summary.join(" · ")}`);
out.push("");
out.push("Each row links its rationale doc. Status lives in that doc's");
out.push("`> **Status:**` header; this table is regenerated from those headers.");
out.push("");

for (const status of ORDER) {
  const group = rows.filter((r) => r.status === status);
  if (!group.length) continue;
  const refCol = { DONE: "Shipped", PARTIAL: "Remaining", REFERENCE: "Note", DECLINED: "Reason" }[status];
  out.push(`## ${HEADING[status]}`);
  out.push("");
  // OPEN is a plain 3-column list; its Ref field (if any) is not surfaced —
  // scheduling nuance belongs in the linked doc's body.
  const withRef = status !== "OPEN";
  out.push(withRef ? `| # | Title | Area | ${refCol} |` : "| # | Title | Area |");
  out.push(withRef ? "|---|---|---|---|" : "|---|---|---|");
  for (const r of group) {
    const cells = [`[${r.num}](${r.file})`, r.title, r.area];
    if (withRef) cells.push(r.ref || "—");
    out.push(`| ${cells.join(" | ")} |`);
  }
  out.push("");
}

out.push("## Adding an entry");
out.push("");
out.push("Create `NN-slug.md` with a `# Title` and, directly under it, one");
out.push("blockquote line (fields joined by ` · `):");
out.push("");
out.push("```");
out.push("> **Status:** OPEN · **Area:** frontend");
out.push("```");
out.push("");
out.push("`Status` ∈ OPEN · PARTIAL · DONE · REFERENCE · DECLINED. `Area` is one or");
out.push("more of frontend, rust, ports, conformance, spec, infra, docs. `**Ref:**`");
out.push("(free text) is optional — shown for PARTIAL/DONE/REFERENCE/DECLINED, not");
out.push("for OPEN. `mise run docs` fails if the header is missing or malformed;");
out.push("rerun `mise run docs:backlog-index` to refresh this file.");

process.stdout.write(out.join("\n").replace(/\n+$/, "\n"));
EOF
)

if [ "$fix" -eq 1 ]; then
    printf '%s\n' "$generated" > "$out"
    printf '%s\n' "wrote $out"
    exit 0
fi

if ! printf '%s\n' "$generated" | diff -u "$out" - >/dev/null 2>&1; then
    printf '%s\n' "$out is stale — run: mise run docs:backlog-index" >&2
    printf '%s\n' "$generated" | diff -u "$out" - >&2 || true
    exit 1
fi
printf '%s\n' "docs/feature-backlog/README.md is current"
